import { Rook , Bishop , Pawn ,  Queen , King , Knight , Position , Square  , Empty} from "./Peices.js"

export default class Board{
    constructor() {
        this.board = [
            [new Square(new Rook(new Position('a', 1) , 'W') , false),
            new Square(new Knight(new Position('b', 1) , 'W') , false),
            new Square(new Bishop(new Position('c', 1) , 'W'), false),
            new Square(new Queen(new Position('d', 1) , 'W'), false),
            new Square(new King(new Position('e', 1) , 'W'), false),
            new Square(new Bishop(new Position('f', 1) , 'W'), false),
            new Square(new Knight(new Position('g', 1) , 'W'), false),
            new Square(new Rook(new Position('h', 1) , 'W'), false)],
            [new Square(new Pawn(new Position('a' , 2) , 'W'), false),
            new Square(new Pawn(new Position('b' , 2) , 'W'), false),
            new Square(new Pawn(new Position('c' , 2) , 'W'), false) ,
            new Square(new Pawn(new Position('d' , 2) , 'W'), false),
            new Square(new Pawn(new Position('e' , 2) , 'W'), false), 
            new Square(new Pawn(new Position('f' , 2) , 'W'), false),
            new Square(new Pawn(new Position('g' , 2) , 'W'), false),
            new Square(new Pawn(new Position('h' , 2) , 'W'), false)],
            [ new Square( Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),],
            [ new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),],
            [new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),],
            [new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),
                new Square(Empty , true),],
            [new Square(new Pawn(new Position('a' , 7) , 'B'), false),
                new Square(new Pawn(new Position('b' , 7) , 'B'), false),
                new Square(new Pawn(new Position('c' , 7) , 'B'), false) ,
                new Square(new Pawn(new Position('d' , 7) , 'B'), false),
                new Square(new Pawn(new Position('e' , 7) , 'B'), false), 
                new Square(new Pawn(new Position('f' , 7) , 'B'), false),
                new Square(new Pawn(new Position('g' , 7) , 'B'), false),
                new Square(new Pawn(new Position('h' , 7) , 'B'), false)],
            [new Square(new Rook(new Position('a', 8) , 'B') , false),
            new Square(new Knight(new Position('b', 8) , 'B') , false),
            new Square(new Bishop(new Position('c', 8) , 'B'), false),
            new Square(new Queen(new Position('d', 8) , 'B'), false),
            new Square(new King(new Position('e', 8) , 'B'), false),
            new Square(new Bishop(new Position('f', 8) , 'B'), false),
            new Square(new Knight(new Position('g', 8) , 'B'), false),
            new Square(new Rook(new Position('h', 8) , 'B'), false)],
        ]
    
    }

    showBoard(){ 
        console.log(this.board)
    };
}

